CREATE TABLE IF NOT EXISTS PEOPLE (
    id INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    ADDRESS VARCHAR(255) NOT NULL
);
--Just in case
DELETE FROM PEOPLE;
INSERT INTO PEOPLE(NAME, ADDRESS) VALUES ('foo', '123 Nice Street');